l=[24,49,9,80,1,29,73,61,31,93,87]
m=["france","king","red","babylon","SRIBASCHHA","subudhi"]
n=[12,'rest',75,'tree',24,'house','']
#print(len(n))
#m.append(20)
#print(m)       #m=["france","king","red","babylon","SRIBASCHHA","subudhi",20]
#l.extend([56,92,64])
#print(l)       #l=[24, 49, 9, 80, 1, 29, 73, 61, 31, 93, 87, 56, 92, 64]
#print(l.pop())
#print(l)
#n.append([43,'car'])
#print(n)
#del l[4:9]
#print(l)
#m.remove("red")
#print(m)
#n.insert(4,31)
#print(n)
#n.reverse()
#print(n)
#m.sort()
#print()
#print(sum(l))
n=413
n=str(n)
print(list(n))